[direct]

add = [
    "favicon.yandex.net",
    "res.res.res.res",
    "steamcontent.com",
    "googleapis.cn",
]

remove = []

[proxy]

add = []

remove = ["xn--ngstr-lra8j.com", "google.cn", "googleapis.cn"]
