[direct]

add = [
    "favicon.yandex.net",
    "res.res.res.res",
    "steamcontent.com",
    "googleapis.cn",
    "regexp:^r+[0-9]+(---|\.)sn-(2x3|ni5|j5o)\w{5}\.googlevideo\.com$",
    "regexp:^r+[0-9]+(---|\.)sn-(2x3|ni5|j5o)\w{5}\.xn--ngstr-lra8j\.com$"
]

remove = []

[proxy]

add = []

remove = ["xn--ngstr-lra8j.com", "google.cn"]
